// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9SjQoXbDc6fZPKYmd0K8r8wOVmg4AMDw',
    appId: '1:945426936921:web:7267bf282ee83b44dced48',
    messagingSenderId: '945426936921',
    projectId: 'campusbuddy-ucc',
    authDomain: 'campusbuddy-ucc.firebaseapp.com',
    storageBucket: 'campusbuddy-ucc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABUTRdG43_ZDqRZQ1z-LvhGlrsFcHTQ3s',
    appId: '1:945426936921:android:37803f3eb1611bc2dced48',
    messagingSenderId: '945426936921',
    projectId: 'campusbuddy-ucc',
    storageBucket: 'campusbuddy-ucc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSY4hkhv1y7GIwCEOHT67axyVrHwfOhSo',
    appId: '1:945426936921:ios:0fd8a6517bd29033dced48',
    messagingSenderId: '945426936921',
    projectId: 'campusbuddy-ucc',
    storageBucket: 'campusbuddy-ucc.firebasestorage.app',
    iosBundleId: 'com.example.campusbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSY4hkhv1y7GIwCEOHT67axyVrHwfOhSo',
    appId: '1:945426936921:ios:0fd8a6517bd29033dced48',
    messagingSenderId: '945426936921',
    projectId: 'campusbuddy-ucc',
    storageBucket: 'campusbuddy-ucc.firebasestorage.app',
    iosBundleId: 'com.example.campusbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9SjQoXbDc6fZPKYmd0K8r8wOVmg4AMDw',
    appId: '1:945426936921:web:060f39f3b452ad53dced48',
    messagingSenderId: '945426936921',
    projectId: 'campusbuddy-ucc',
    authDomain: 'campusbuddy-ucc.firebaseapp.com',
    storageBucket: 'campusbuddy-ucc.firebasestorage.app',
  );
}
